# Generated by Django 4.1.7 on 2023-03-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preview_app.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('fichier_pptx', models.CharField(max_length=60)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preview_app.session')),
            ],
        ),
        migrations.CreateModel(
            name='InterPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preview_app.intervenant')),
                ('id_presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preview_app.presentation')),
            ],
        ),
    ]
