# Generated by Django 4.1.7 on 2023-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenant',
            name='photo',
        ),
        migrations.AddField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='statics/images'),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
