# Generated by Django 4.1.7 on 2023-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0002_remove_intervenant_photo_conference_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='preview_app/statics/images'),
        ),
    ]
