# Generated by Django 4.1.7 on 2023-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0003_alter_conference_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
