# Generated by Django 4.1.7 on 2023-03-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0004_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='preview_app/static/images'),
        ),
        migrations.AlterField(
            model_name='jour',
            name='date',
            field=models.DurationField(primary_key=True, serialize=False),
        ),
    ]
