# Generated by Django 4.1.7 on 2023-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0005_alter_conference_logo_alter_jour_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='date',
        ),
        migrations.AlterField(
            model_name='jour',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
