# Generated by Django 4.1.7 on 2023-04-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0006_alter_jour_date_alter_session_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='date',
        ),
    ]
