# Generated by Django 4.1.7 on 2023-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_app', '0007_remove_salle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='session',
            name='duree',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
